### ISSUE TITLE
Latest rasterio could not load mbtiles plugin.

### ISSUE THREAD

**Issue by kn-id** [mapbox/rio-mbtiles#39]
tested with rasterio v1.0.2 on Ubuntu 16.04

```
$ rio mbtiles --help
  Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/click_plugins/core.py", line 37, in decorator
      group.add_command(entry_point.load())
    File "/home/kn/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2321, in load
      return self.resolve()
    File "/home/kn/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2327, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/local/lib/python3.5/dist-packages/mbtiles/scripts/cli.py", line 13, in <module>
      from rasterio.rio.options import force_overwrite_opt, output_opt
  ImportError: cannot import name 'force_overwrite_opt'
```

**Comment by sgillies** [comment]
Fixed in 1.4.0.

**Comment by bernatfortet** [comment]
Getting the same error:
rio-mbtiles: 1.6
MacOS: 12.6.3 (21G419)

```
rio mbtiles --help

Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/bernat/miniconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernat/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/mbtiles/scripts/cli.py", line 18, in <module>
    from shapely.geometry import mapping, shape
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/shapely/geometry/base.py", line 19, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/bernat/global_envs/global_venv/lib/python3.11/site-packages/shapely/geos.py", line 112, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.dylib'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernat/miniconda3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/bernat/global_envs/global_venv/lib/libgeos_c.dylib, 0x0006): tried: '/Users/bernat/global_envs/global_venv/lib/libgeos_c.dylib' (no such file)
```
Thanks!

**Comment by bernatfortet** [comment]
With some GPT help I was able to figured that I needed:
- install GDAL
- re-install rasterio
- and have Shapely 1.7.1 instead of Shapely 2.x.x
