### ISSUE TITLE
Failed to create zoom 1 tile when source crs is in UTM projection

### ISSUE THREAD

**Issue by kn-id** [mapbox/rio-mbtiles#41]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/bukapeta/python-dev/ENV/lib/python3.6/site-packages/mbtiles/__init__.py", line 66, in process_tile
    tile_window = tile_window.round_offsets().round_shape()
  File "/data/bukapeta/python-dev/ENV/lib/python3.6/site-packages/rasterio/windows.py", line 691, in round_offsets
    pixel_precision is not None else self.col_off),
ValueError: cannot convert float NaN to integer
```

I think it's because ```rasterio.warp.transform_bounds``` returned `infinity` number
https://github.com/mapbox/rio-mbtiles/blob/master/mbtiles/__init__.py#L58

```python
import rasterio
rasterio.warp.transform_bounds('EPSG:3857', 'EPSG:32749', 0.0, -20037508.342789255, 20037508.342789244, -7.081154551613622e-10)
```
returned `(-14601517.568011362, -9093361.687045071, inf, inf)`

**Comment by sgillies** [comment]
Confirmed @kn-id . I've got the fix for this and it will be appearing in version 1.4.1 later today. Thanks for your patience!
