### ISSUE TITLE
rio mbtiles MemoryError

### ISSUE THREAD

**Issue by FreeGIS** [mapbox/rio-mbtiles#49]
tif size:3G
ram:centos 7 1G VMware
`time rio mbtiles town.tif -o ttt.mbtiles --zoom-levels 11..18 -j 3 -f PNG`

the result:
`
WARNING:rasterio._env:CPLE_NotSupported in driver PNG does not support creation option SHARING
WARNING:rasterio._env:CPLE_NotSupported in driver PNG does not support creation option SHARING
WARNING:rasterio._env:CPLE_NotSupported in driver PNG does not support creation option SHARING
WARNING:rasterio._env:CPLE_NotSupported in driver PNG does not support creation option SHARING
WARNING:rasterio._env:CPLE_NotSupported in driver PNG does not support creation option SHARING
Traceback (most recent call last):
  File "/usr/bin/rio", line 11, in <module>
    load_entry_point('rasterio==1.0.24', 'console_scripts', 'rio')()
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rio_mbtiles-1.4.2-py2.7.egg/mbtiles/scripts/cli.py", line 214, in mbtiles
    for tile, contents in pool.imap_unordered(process_tile, tiles):
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
MemoryError
`

The tool cause my vm to slow...

so i develop a tif tile tool with  node-gdal:
`/opt/gdaltest/tiles/18/159699/135273.png
/opt/gdaltest/tiles/18/159699/135274.png
/opt/gdaltest/tiles/18/159699/135275.png
/opt/gdaltest/tiles/18/159699/135276.png
/opt/gdaltest/tiles/18/159699/135277.png
/opt/gdaltest/tiles/18/159699/135278.png
/opt/gdaltest/tiles/18/159699/135279.png
/opt/gdaltest/tiles/18/159699/135280.png
切片耗时: 303600.441ms
`
the tool runs ok and run faster(Asynchronous io?),so i think the rio mbtiles so slow may be had performance problem

**Comment by sgillies** [comment]
It says in the readme that rio-mbtiles is only suitable for medium sized rasters up to about 1 GB uncompressed. This is because the command loads the entire image into memory.
