### ISSUE TITLE
rasterio._err.CPLE_NotSupportedError: Cannot find coordinate operations

### ISSUE THREAD

**Issue by dazza-codes** [mapbox/rio-mbtiles#50]
Works OK on `pyproj==2.2.*` but not on `pyproj>=2.3.*`
- assuming `pyproj` is the key library involved in this bug, not entirely sure about that
- `pyproj==2.2.*` and `pyproj==2.3.*` should both use `proj==6.1.*`

```
$ pip freeze | grep -E -i 'rasterio|proj|gdal|geopandas|crs'
GDAL==3.0.1
geopandas==0.6.2
pyproj==2.3.1
rasterio==1.1.0
```

I should add that conda is used to install almost everything and subsequently pip is used to install `rio-mbtiles` (maybe a conda-forge package for `rio-mbtiles` is an option?).

The command with `-j 3` on a 4-physical-core system fails (backtrace below) and with `-j 1` it is OK, i.e. the command works with:
```
    rio mbtiles -j 1 \
      --format PNG --rgba --overlay --overwrite \
      --resampling nearest \
      --title "${title}" \
      "$input" -o "$output"
```

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/mbtiles/__init__.py", line 89, in process_tile
    resampling=resampling)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/env.py", line 394, in wrapper
    return f(*args, **kwds)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/env.py", line 620, in wrapper
    return f(*args, **kwds)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/warp.py", line 347, in reproject
    warp_mem_limit=warp_mem_limit, **kwargs)
  File "rasterio/_warp.pyx", line 480, in rasterio._warp._reproject
  File "rasterio/_warp.pyx", line 460, in rasterio._warp._reproject
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_NotSupportedError: Cannot find coordinate operations from 'PROJCRS["unnamed",BASEGEOGCRS["Normal Sphere (r=6370997)",DATUM["unknown",ELLIPSOID["sphere",6370997,0,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]],CONVERSION["unnamed",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",19.6181716918945,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",-153.800003051758,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",10,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",30,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",0,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",0,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["northing",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]' to 'EPSG:3857'
"""
```

Using `-j 2` got a different error, i.e.
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 363, in rasterio._crs._CRS.from_user_input
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/mbtiles/__init__.py", line 65, in process_tile
    with memfile.open(**kwds) as tmp:
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/env.py", line 394, in wrapper
    return f(*args, **kwds)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/io.py", line 136, in open
    nodata=nodata, sharing=sharing, **kwargs)
  File "rasterio/_io.pyx", line 2000, in rasterio._io.BufferedDatasetWriterBase.__init__
  File "rasterio/_io.pyx", line 1247, in rasterio._io.DatasetWriterBase._set_crs
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/rasterio/crs.py", line 459, in from_user_input
    obj._crs = _CRS.from_user_input(value, morph_from_esri_dialect=morph_from_esri_dialect)
  File "rasterio/_crs.pyx", line 367, in rasterio._crs._CRS.from_user_input
rasterio.errors.CRSError: The WKT could not be parsed. OGR Error code 6
"""
```

There seems to be some multiprocessing (IPC?) problems.

**Comment by sgillies** [comment]
rio-mbtiles' only direct dependencies are click, mercantile, numpy, and rasterio. It doesn't use pyproj or geopandas. Those errors look like the symptoms of a corrupted conda environment. I suggest deleting the environment and re-creating it to get a good, consistent set of packages. If you can reproduce the problem once you have GDAL 3.0.4 and rasterio 1.1.3, please reopen this issue.
